# Default values for nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

service:
  name: helm-mynginx-svc
  app: helm-mynginx
  type: ClusterIP
  port: 80

deployment:
  name: helm-mynginx-deploy
  app: helm-mynginx
  image: nginx
  tages: latest
  port: 80